project:
  type: website

website:
  #title: "PreFer"
  open-graph: true
  site-url: https://www.gertstulp.com/
  repo-url: https://github.com/lisasivak/prefer
  image: images/PreFer_logo_no_text2.png
  favicon: images/PreFer_logo_favicon.png
  navbar:
    background: "#f0eeeb"
    logo: images/PreFer_logo_no_text2.png
    #logo-alt: "should be a picture of GS"
    #title: "Pre<span class='icon-line'></span>Fer"
    collapse-below: lg
    right:
      #- research/index.qmd
      #- posts/index.qmd
      #- CV/index.qmd
      #- resources/index.qmd
      #- text: "Other"
      #  menu: 
      #  - text: "Some notes"
      #    href: other/about.qmd
      #  - text: "copy-paste"
      #    href: other/copypaste.qmd
      #- text: "About PreFer"
      #  href: "#about-prefer"
      - text: "APPLY"
        href: details/overview/3application.md
      - text: "Important dates"
        href: "#important-dates"
      #- text: "The aim"
      #  href: "#the-aim"
      #- text: "Why participate"
      #  href: "#why-participate"
      - text: "How to participate"
        href: "#how-to-participate"
      - text: "Preprint"
        href: https://arxiv.org/abs/2402.00705
      #- text: "Methodology"
      #  href: "#about-prefer"
      - faq/index.qmd
      - posts/index.qmd
      - text: "Organizers"
        menu: 
        - text: "Who we are"
          href: about-us.qmd
        - text: "Contact us"
          href: contact.qmd
      #    href: contact.qmd
      #  - text: "Why participate"
      #    href: "#why participate"
      #  - text: "Organisers"
      #    href: "#organisers"
      #  - text: "Details about the challenge"
      #    href: "#details"
      
  #sidebar: 
  #   - title: "About us"
  #     contents:
  #       - about-us.qmd
  #       - contact.qmd
  #       - viewpoints/editors-blog/posts/2022/10/18/meet-the-team.qmd
  #       - rwds-partners.qmd
  #       - contact.qmd
  #       - ts-and-cs.qmd
  #   - title: "Call for contributions"
  #     contents:
  #       - contributor-docs/call-for-contributions.qmd
  #       - contributor-docs/case-studies.qmd
  #       - contributor-docs/explainers.qmd
  #       - contributor-docs/exercises.qmd
  #       - contributor-docs/datasets.qmd
  #       - contributor-docs/training-guides.qmd
  #       - contributor-docs/recommender.qmd
  #       - contributor-docs/datasciencebites.qmd
  #       - contributor-docs/contributor-guidelines.qmd
  #       - contributor-docs/style-guide.qmd
  #   - title: "Careers"
  #     contents:
  #       - careers/index.qmd
  #       - careers/career-profiles/index.qmd
  #   - title: "Ideas"
  #     contents:
  #       - ideas/index.qmd
  #       - ideas/tutorials/index.qmd
  #       - ideas/datasciencebites/index.qmd
  #   - title: "Viewpoints"
  #     contents: 
  #       - viewpoints/index.qmd
  #       - viewpoints/editors-blog/index.qmd
  #       - viewpoints/interviews/index.qmd
  #       - href: viewpoints/newsletter/index.qmd
  #         text: Newsletter

  page-navigation: true

  page-footer:
    background: "#000000"
    left: |
      PreFer data challenge  
      The website is based on [Real World Data Science](https://realworlddatascience.net/){target="_blank"}  
      
    #center:  
    #  - href: mailto:g.stulp@rug.nl
    #    icon: envelope
    #    aria-label: envelope
    #  - href: https://github.com/gertstulp
    #    icon: github
    #    aria-label: GitHub
    #  - href: https://scholar.google.nl/citations?user=fFcVaEYAAAAJ&hl=nl
    #    text: "{{< ai google-scholar >}}"
    #    aria-label: Scholar
    #  - href: https://orcid.org/0000-0003-0173-5554
    #    text: "{{< ai orcid >}}"
    #    aria-label: Orcid
    right: |
      The map of the Netherlands by [Tananuphong Kummaru on Vecteezy](https://www.vecteezy.com/png/18876571-polygonal-netherlands-map){target="_blank"}
    
format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true

editor: source

execute: 
  freeze: auto
